spring:
  datasource:
    druid:
      url: jdbc:mysql://cdb-csnz8qhs.cd.tencentcdb.com:10087/blog_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: code-fusheng
#      url: jdbc:mysql://175.24.45.179:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#      username: root
#      password: sa123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: xyz.fusheng
server:
  port: 8001


# spring:
#  datasource:
#    url: jdbc:mysql://175.24.45.179:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
#    username: root
#    password: sa123
#    driver-class-name: com.mysql.cj.jdbc.Driver
